name: streamlit
channels:
  - conda-forge
dependencies:
  - python = 3.8
  - numpy
  - pandas
  - av
  - Pillow
  - pytorch
  - torchvision
  - scikit-image
  - imutils
  - opencv
  - streamlit
  - typing_extensions
  - pip:
    - playsound
    - streamlit_webrtc
    - aiortc
